---
title: "Modeling Udemy Course Popularity"
output:
  html_document: 
    theme: readable
    toc: yes
  pdf_document: default
urlcolor: cyan
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
options(
  scipen = 1,
  digits = 4,
  width = 80,
  fig.align = "center"
)
```

***
*** Delete before submitting

The report should begin with the title of the project.  

Do not include the names of the group members at the outset of the report. 

***

## Introduction

***
*** Delete before submitting

The introduction section should relay what you are attempting to accomplish.  

It would include a statement of the business, science, research, or personal interest you have that leads to analyzing the data you’ve chosen.  

It should provide enough background to your work such that a reader would not need to load your data to understand your report.  

Like the simulation project, you can assume the reader is familiar with the course concepts, but not your data.  

Some things to consider: 

What is this data?  

Where did it come from?  

What are the variables?  

Why is it interesting to you? 

Why are you creating a model for this data?  

What is the goal of this model? 

***



## Methods

***
*** Delete before submitting

The methods section should contain the bulk of your “work.” This section will contain the bulk of the R code that is used to generate the results. Your R code is not expected to be perfect idiomatic R, but it is expected to be understood by a reader without too much effort. Use RMarkdown and code comments to your advantage to explain your code if needed. 

This section should contain any information about data preparation that is performed to the original data before modelling. Then you will apply methods seen in class, which may include some of the following but are not limited to: 

Multiple linear regression 

Dummy variables 

Interaction 

Residual diagnostics 

Outlier diagnostics 

Transformations 

Polynomial regression 

Model selection 


Your task is not to use as many methods as possible. Your task is to use appropriate methods to find a good model that can correctly answer a question about the dataset, and then to communicate your result effectively. Some possible items to be discussed: 

Description of the original data file including description of all relevant variables. 

Description of additional data preparation that you performed. 

Description of the process you chose to follow. 

Narrative of your step-by-step decision making process throughout the analysis as you adjusted the model and attempted to validate model assumptions. 

***


## Results

***
*** Delete before submitting

The results section should contain numerical or graphical summaries of your results. 

You should report a final model you have chosen.  

There is not necessarily one, singular correct model, but certainly some methods and models are better than others in certain situations. You may use any methods we studied this semester to complete this task, and provide evidence that your final choice of model is a good one.  

Some possible items to be discussed: 

***


## Discussion

***
*** Delete before submitting

The discussion section should contain discussion of your results and should frame your results in the context of the data.  

How is your final model useful? 

***

## Appendix

***
*** Delete before submitting

The appendix section should contain code and analysis that is used, but that would have otherwise cluttered the report or is not directly related to the choice of model.  

Do not simply dump code in here.  

Only utilize the appendix to supplement the primary focus of the report.  

The appendix should also conclude with the names of the group members. 

***

Group Members: Amanda Wang, Anand Kumar, Dani Richmond

